CREATE DATABASE BANCO_TESTE
USE BANCO_TESTE
GO
CREATE TABLE FILIAL(
ID INT IDENTITY PRIMARY KEY,
CNPJ_Filial CHAR(11),
Cidade VARCHAR(50)
)
GO
CREATE TABLE VENDEDORES(
ID INT IDENTITY PRIMARY KEY,
idFilial INT REFERENCES FILIAL(ID),
nomeVendedor VARCHAR(50),
CPF CHAR(11),
Endereco VARCHAR(50)
)
GO
CREATE TABLE CLIENTES(
ID INT IDENTITY PRIMARY KEY,
nomeCliente VARCHAR(50),
CPF CHAR(11),
Endereco VARCHAR(50),
posicaoGeografica GEOGRAPHY
)
GO
CREATE TABLE PEDIDOS(
ID INT IDENTITY PRIMARY KEY,
idVendedor INT REFERENCES VENDEDORES(ID),
idCliente INT REFERENCES CLIENTES(ID),
valorPedido MONEY,
dataPedido DATETIME DEFAULT GETDATE(),
dataEntrega DATETIME
)
GO
CREATE TABLE VENDAS(
ID INT IDENTITY PRIMARY KEY,
idPedido INT REFERENCES PEDIDOS(ID),
dataVenda DATETIME DEFAULT GETDATE(),
valorVenda MONEY
)
GO
CREATE TABLE PRODUTOS(
ID INT IDENTITY PRIMARY KEY,
nomeProduto VARCHAR(50),
custoProduto MONEY,
precoProduto MONEY,
qtdPruduto INT CHECK(qtdPruduto > 0)
)
GO
CREATE TABLE PECAS(
ID INT IDENTITY PRIMARY KEY,
nomePeca VARCHAR(50),
custoPeca MONEY,
qtdPeca INT CHECK (qtdPeca >0)
)
GO
CREATE TABLE MONTAGEM(
ID INT IDENTITY PRIMARY KEY,
idPedido INT REFERENCES PEDIDOS(ID),
idProduto INT REFERENCES PRODUTOS(ID),
idPeca INT REFERENCES PECAS(ID),
valorProduto MONEY,
quantidadeProduto INT
)
