--Tables: 8
--Tuplas: 20 para cada tabela
--Filial, Vendedores, Clientes, Pedidos, Vendas, Produtos, Pecas e Montagem

CREATE TABLE FILIAL(
	IDD 			number 			NOT NULL,
	cnpj_filial 	CHAR(11) 		UNIQUE NOT NULL,
	cidade 			VARCHAR(50) 	NOT NULL,
	uf     			CHAR(2)      	NOT NULL,
	regiao 			VARCHAR(50)     NOT NULL,
	CONSTRAINT pk_FILIAL PRIMARY KEY (IDD, cidade)
);

CREATE TABLE CLIENTES(
	IDD 			number 			NOT NULL,
	nomeCliente 	VARCHAR(50) 	NOT NULL,
	cpf 			CHAR(11) 		UNIQUE NOT NULL,
	endereco 		VARCHAR(50) 	NOT NULL,
	cidade 			VARCHAR(50) 	REFERENCES FILIAL(cidade) NOT NULL,
	CONSTRAINT pk_CLIENTES PRIMARY KEY (IDD, cidade),
	CONSTRAINT fk_cidade FOREIGN KEY (cidade) REFERENCES FILIAL(cidade)
);

CREATE TABLE VENDEDORES(
	IDD 			number 			PRIMARY KEY NOT NULL,
	idFilial 		INT 			REFERENCES FILIAL(IDD) NOT NULL,
	nomeVendedor 	VARCHAR(50) 	NOT NULL,
	cpf 			CHAR(11) UNIQUE NOT NULL,
	endereco 		VARCHAR(50) 	NOT NULL
);

CREATE TABLE PEDIDOS(
	IDD 			number 			PRIMARY KEY NOT NULL,
	idVendedor 		INT 			REFERENCES VENDEDORES(IDD) NOT NULL,
	idCliente 		INT 			REFERENCES CLIENTES(IDD) NOT NULL,
	valorPedido 	NUMBER(5,2) 	NOT NULL,
	dataPedido 		date 			NOT NULL,
	dataEntrega 	date 			NOT NULL
);

CREATE TABLE VENDAS(
	IDD 			number 			PRIMARY KEY NOT NULL,
	idPedido 		INT 			REFERENCES PEDIDOS(IDD) NOT NULL,
	dataVenda 		date 			NOT NULL,
	ownerVenda 		VARCHAR(50) 	NOT NULL,
	valorVenda 		INT 			NOT NULL
);

CREATE TABLE PRODUTOS(
	IDD 			number 			PRIMARY KEY NOT NULL,
	nomeProduto 	VARCHAR(50) 	NOT NULL,
	custoProduto 	int 			NOT NULL,
	precoProduto 	int 			NOT NULL,
	qtdProduto 		INT 			CHECK(qtdProduto > 0) NOT NULL
);

CREATE TABLE PECAS(
	IDD 			number 			PRIMARY KEY NOT NULL,
	nomePeca 		VARCHAR(50) 	NOT NULL,
	custoPeca 		int 			NOT NULL,
	dataFabPeca 	date 			NOT NULL,
	qtdPeca 		INT 			CHECK (qtdPeca >0) NOT NULL
);

CREATE TABLE MONTAGEM(
	IDD 			number 			PRIMARY KEY NOT NULL,
	idPedido 		INT 			REFERENCES PEDIDOS(IDD) NOT NULL,
	idProduto 		INT 			REFERENCES PRODUTOS(IDD) NOT NULL,
	idPeca 			INT 			REFERENCES PECAS(IDD) NOT NULL,
	valorProduto 	NUMBER(5,2) 	NOT NULL,
	qtdProduto 		INT 			CHECK (qtdProduto > 0) NOT NULL
);

-- DROP TABLE FILIAL CASCADE CONSTRAINTS;
-- DROP TABLE CLIENTES CASCADE CONSTRAINTS;
-- DROP TABLE VENDEDORES CASCADE CONSTRAINTS;
-- DROP TABLE PEDIDOS CASCADE CONSTRAINTS;
-- DROP TABLE VENDAS CASCADE CONSTRAINTS;
-- DROP TABLE PRODUTOS CASCADE CONSTRAINTS;
-- DROP TABLE PECAS CASCADE CONSTRAINTS;
-- DROP TABLE MONTAGEM CASCADE CONSTRAINTS;